---

image: debian:latest

stages:
  - lint

before_script:
  - apt-get -qq update
  - apt-get -qq install -y python3 python3-pip
  - pip3 install yamllint ansible-lint

ansible-lint:
  stage: lint
  script:
    - ansible-lint .

yaml-lint:
  stage: lint
  script:
    - yamllint .
