---

- name: Generate candidate primes DH key exchange
  command: "ssh-keygen -G /etc/ssh/moduli.candidates -b {{ sshd.meta.regenerateDHParamsBits }}"
  args:
    creates: '/etc/ssh/moduli.candidates'
  register: sshd_moduli_candidates
  when: sshd__generate_dh_params

- name: Test candidate primes for DH key exchange for safety
  command: "ssh-keygen -T /etc/ssh/moduli -f /etc/ssh/moduli.candidates"
  when: sshd_moduli_candidates.changed
  notify: restart sshd
  tags: ['skip_ansible_lint']

- name: Place DH params
  copy:
    owner: root
    group: root
    mode: 0644
    src: files/moduli
    dest: /etc/ssh/moduli
  when: not sshd__generate_dh_params
  notify: restart sshd

- name: Place banner
  copy:
    content: "{{ sshd__banner_text }}"
    dest: "{{ sshd__banner_file }}"

- name: Place sshd configuration
  template:
    owner: root
    group: root
    mode: 0640
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: sshd_config.j2, dest: /etc/ssh/sshd_config}
  notify:
    - validate sshd configuration
